name: identity_verification_flutter_ios
description: "iOS implementation of the identity_verification_flutter plugin."
version: 0.1.1
publish_to: none # CI 发布时自动移除
homepage: https://github.com/jeromexiong/identity_verification_flutter

environment:
  sdk: ^3.12.0
  flutter: ">=3.44.0"

flutter:
  plugin:
    implements: identity_verification_flutter
    platforms:
      ios:
        pluginClass: TencentIdentityVerificationPlugin
        dartPluginClass: IdentityVerificationIos
        swiftPackageManager:
          enabled: true

dependencies:
  flutter:
    sdk: flutter
  identity_verification_flutter_platform_interface:
    path: ../identity_verification_flutter_platform_interface

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
